### ISSUE TITLE
Lua Error at login - unexpected symbol

### ISSUE THREAD

**Issue by kepheuswow** [funkydude/ErrorMonster#5]
## Describe the problem
Getting the following error, when I log in (see screenshot). 
Interface\AddOns\ErrorMonster\Locales\enUS.lua:2: unexpected symbol near `...'

### What steps will reproduce the problem?

1.  copy ErrorMonster folder into Interface\Addons folder
2.  login with character
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![1657565917](https://user-images.githubusercontent.com/109022888/178338534-736609cf-e7fa-4039-a9c0-150ac3e74d76.jpg)

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.2.3

**Comment by funkydude** [comment]
There is nothing in the code that could cause this. Please delete the entire addon and install it fresh, preferably using the CurseForge app to avoid issues.

**Comment by kepheuswow** [comment]
Doesn't work because it's for 1.13/1.14. 

So this Addon doesn't work for Vanilla (1.12)? On GitHub you named the file ErrorMonster_Vanilla.toc. So I tought the Addon is for Vanilla (1.12). But inside it says Interface: 11403 (1.14.3).

So it's a bit misleading. You should rename it to ErrorMonster_Classic.toc. Classic != Vanilla
