### ISSUE TITLE
'Addon has been blocked' frame

### ISSUE THREAD

**Issue by jonomurphy** [funkydude/ErrorMonster#6]
Hi there,

Is it possible to remove the screen that appears stating 'Addon has been blocked from using a Blizzard' blabla?

**Comment by funkydude** [comment]
Sorry, this addon is for character errors not blocking popups.

**Comment by jonomurphy** [comment]
Apologies. Would you be able to advise a way to block them? Thanks for clarifying.

**Comment by funkydude** [comment]
Not really. That's a result of addons intentionally or accidentally interfacing with things they shouldn't. It's up to the addon developer to fix the issue. I'd suggesting reporting it to the developer who will probably ask you for a taint log to try and track down the issue.

**Comment by jonomurphy** [comment]
Thanks a lot!
