### ISSUE TITLE
sending output to blizzard combat text?

### ISSUE THREAD

**Issue by rakkarage** [funkydude/ErrorMonster#7]
## Describe the problem

it used to be an option to send output to blizzard combat text?
i cannot see that option now tho i still see sticky which was part of that?

### What steps will reproduce the problem?

1.  open options
2.  no options for blizzard combat text

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![WoWScrnShot_110622_210732](https://user-images.githubusercontent.com/962340/200212174-ad068c98-d100-4380-ad56-24239ccdf2af.jpg)

### What version of the addon are you using? (Stating 'latest' is not useful)

ErrorMonster-v10.0.0.zip

**Comment by funkydude** [comment]
Interesting, this must have silently broke in Dragonflight. Thanks for bringing this up, looking into it.

**Comment by funkydude** [comment]
New version released with a fix, thanks!
