### ISSUE TITLE
None + Sound?

### ISSUE THREAD

**Issue by rakkarage** [funkydude/ErrorMonster#8]
## Describe the problem

if you set output to none the sound stops too? is it possible to hide text but keep limited audio? or maybe i am doing something wrong?

### What steps will reproduce the problem?

1.  set output to anything but none and hear error sounds
2.  set output to none and hear none?

### What version of the addon are you using? (Stating 'latest' is not useful)

ErrorMonster-v10.0.0.zip

**Comment by funkydude** [comment]
This is intentional for people that want to kill it entirely. The only way to accomplish this would be to set it to something that's not visible.
