### ISSUE TITLE
Small stutters while looting

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [funkydude/ErrorMonster#9]
## Describe the problem
The issue I am having is when looting a mob the game stutters, and pauses for a moment around 0.80 of a second when looting. 

### What steps will reproduce the problem?

1.  Activate Error Monster, kill mob, loot.
2.  
3.  

### Do you have an error log of what happened?
No errors are being thrown, it is the strangest thing, turn error monster on, loot lag, turn it off, gone.

**Comment by funkydude** [comment]
This addon doesn't do anything when looting. I'd suggest you try the opposite, disable all your other addons except this and see if it still occurs.
